import { createClient } from '@/lib/supabase/server';

export default async function Home() {
  const supabase = await createClient();
  const { data: stocks } = await supabase.from('stocks').select('symbol,slug,company_name').eq('is_active',true).eq('is_indexable',true).order('market_cap',{ascending:false}).limit(12);
  return <div className="container">
    <section className="hero"><div className="eyebrow">US markets · intelligence · predictions</div><h1>See the market with more signal and less noise.</h1><p className="muted">US Market AI brings market data, technical signals, fundamentals, news sentiment and quantitative forecasts into one research platform built for US stocks and crypto.</p><div className="button-row"><a className="button primary" href="/stocks">Explore US Stocks →</a><a className="button" href="/crypto">Explore Crypto</a></div></section>
    <section className="section"><div className="section-head"><div><h2>Market snapshot</h2><p className="muted">Live data modules will populate this dashboard after provider configuration.</p></div></div><div className="grid grid-4"><div className="panel stat-card"><div className="stat-label">S&P 500</div><div className="stat-value">—</div><div className="muted">Waiting for market feed</div></div><div className="panel stat-card"><div className="stat-label">Nasdaq 100</div><div className="stat-value">—</div><div className="muted">Waiting for market feed</div></div><div className="panel stat-card"><div className="stat-label">Market breadth</div><div className="stat-value">—</div><div className="muted">Calculated from universe</div></div><div className="panel stat-card"><div className="stat-label">AI signals</div><div className="stat-value">—</div><div className="muted">Prediction engine coming next</div></div></div></section>
    <section className="section"><div className="section-head"><h2>Popular US stocks</h2><a className="muted" href="/stocks">View all →</a></div><div className="grid grid-4">{(stocks ?? []).map(s=><a className="panel stock-card" href={`/stocks/${s.slug}`} key={s.symbol}><div className="stock-top"><div><div className="ticker">{s.symbol}</div><div className="company">{s.company_name}</div></div><span className="tag">AI READY</span></div><div className="price">—</div><div className="muted">Price data will appear here</div></a>)}{!stocks?.length && <div className="panel stat-card">Database connected. Stock universe will appear here.</div>}</div></section>
    <section className="section"><div className="panel stat-card"><div className="eyebrow">Built for research</div><h2>One page. The complete picture.</h2><p className="muted">Every stock page will combine price action, technicals, fundamentals, earnings, news, quantitative forecasts, prediction history and AI-written analysis.</p></div></section>
  </div>;
}
