import React from 'react';

type Props={financialStatements:any[];dividends:any[];ownership:any[];institutionalHolders:any[];insiderTransactions:any[];monthlyResearch:any[];quarterlyResearch:any[];secFilings:any[];identifiers:any[];provenance:any[];quality:any};
const money=(v:any)=>v==null?'—':`$${Number(v).toLocaleString('en-US',{notation:'compact',maximumFractionDigits:2})}`;
const num=(v:any)=>v==null?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:3});
const pct=(v:any)=>v==null?'—':`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`;
const renderValue=(v:any):React.ReactNode=>{
 if(v==null)return '—';
 if(v instanceof Date)return Number.isNaN(v.getTime())?'—':v.toLocaleDateString('en-US');
 if(typeof v==='object'){try{return JSON.stringify(v)}catch{return String(v)}}
 return v;
};
function Card({id,eyebrow,title,children}:{id?:string;eyebrow:string;title:string;children:React.ReactNode}){return <section className="seo-card" id={id}><div className="seo-card-head"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div></div>{children}</section>}
function Empty({children}:{children:string}){return <div className="seo-empty">{children}</div>}
function period(r:any){return `${r.period_end??r.fiscal_period??'—'}${r.period_type?' · '+String(r.period_type).replaceAll('_',' '):''}`}
function statementRows(rows:any[],type:string){return rows.filter(r=>r.statement_type===type).sort((a,b)=>String(b.period_end??'').localeCompare(String(a.period_end??''))).slice(0,24)}
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div className="seo-data-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{renderValue(v)}</td>)}</tr>)}</tbody></table></div>}

export default function StockDataExpansion({financialStatements,dividends,ownership,institutionalHolders,insiderTransactions,monthlyResearch,quarterlyResearch,secFilings,identifiers,provenance,quality}:Props){
 const income=statementRows(financialStatements,'income_statement'), balance=statementRows(financialStatements,'balance_sheet'), cashflow=statementRows(financialStatements,'cash_flow');
 const displayRows=(rows:any[], limit=24)=>rows.slice(0,limit);
 return <div className="seo-research-stack">
  <Card id="financial-statements" eyebrow="FINANCIAL STATEMENTS" title="Income Statement, Balance Sheet & Cash Flow">
   {financialStatements.length?<><h3>Income Statement</h3>{income.length?<Table headers={['Period','Revenue','Cost of Revenue','Gross Profit','Operating Income','Pretax Income','Net Income','Basic EPS','Diluted EPS','Basic Shares','Diluted Shares']} rows={displayRows(income).map(r=>[period(r),money(r.revenue),money(r.cost_of_revenue),money(r.gross_profit),money(r.operating_income),money(r.pretax_income),money(r.net_income),num(r.eps_basic),num(r.eps_diluted),num(r.shares_basic),num(r.shares_diluted)])}/>:<Empty>Income-statement data is unavailable.</Empty>}
   <h3>Balance Sheet</h3>{balance.length?<Table headers={['Period','Cash','Current Assets','Total Assets','Current Liabilities','Total Liabilities','Debt','Equity']} rows={displayRows(balance).map(r=>[period(r),money(r.cash_and_equivalents),money(r.current_assets),money(r.total_assets),money(r.current_liabilities),money(r.total_liabilities),money(r.total_debt),money(r.shareholders_equity)])}/>:<Empty>Balance-sheet data is unavailable.</Empty>}
   <h3>Cash Flow Statement</h3>{cashflow.length?<Table headers={['Period','Operating CF','CapEx','FCF','Cash','Debt']} rows={displayRows(cashflow).map(r=>[period(r),money(r.operating_cash_flow),money(r.capital_expenditure),money(r.free_cash_flow),money(r.cash_and_equivalents),money(r.total_debt)])}/>:<Empty>Cash-flow data is unavailable.</Empty>}
   </>:<Empty>No normalized financial statements are stored for this stock.</Empty>}
  </Card>
  <Card id="dividend" eyebrow="DIVIDENDS" title="Dividend History & Yield">{dividends.length?<Table headers={['Ex-Date','Record','Payment','Declaration','Amount','Frequency','Currency','Yield','Payout','5Y CAGR','Streak','Source']} rows={dividends.map(d=>[d.ex_date??'—',d.record_date??'—',d.payment_date??'—',d.declaration_date??'—',d.amount==null?'—':`$${Number(d.amount).toFixed(4)}`,d.frequency??'—',d.currency??'USD',pct(d.dividend_yield),pct(d.payout_ratio),pct(d.five_year_cagr),num(d.growth_streak_years),d.data_source??'—'])}/>:<Empty>No dividend rows are stored for this stock.</Empty>}</Card>
  <Card id="ownership" eyebrow="OWNERSHIP" title="Ownership Snapshots">{ownership.length?<Table headers={['Period','Shares Outstanding','Institutional %','Insider %','Float','Institutional Shares','Insider Shares','Source']} rows={ownership.map(o=>[o.period_end??'—',num(o.shares_outstanding),pct(o.institutional_ownership_percent),pct(o.insider_ownership_percent),num(o.float_shares),num(o.institutional_shares),num(o.insider_shares),o.data_source??'—'])}/>:<Empty>No ownership snapshots are stored for this stock.</Empty>}</Card>
  <Card id="institutions" eyebrow="INSTITUTIONAL HOLDERS" title="Top Institutional Holders">{institutionalHolders.length?<Table headers={['Period','Holder','Shares Held','Market Value','Ownership %','Δ Shares','Δ %','Filing Date','Source']} rows={institutionalHolders.map(h=>[h.period_end??'—',h.holder_name??'—',num(h.shares_held),money(h.market_value),pct(h.ownership_percent),num(h.shares_change),pct(h.shares_change_percent),h.filing_date??'—',h.data_source??'—'])}/>:<Empty>No institutional-holder rows are stored for this stock.</Empty>}</Card>
  <Card id="insiders" eyebrow="INSIDER TRANSACTIONS" title="Insider Buying & Selling History">{insiderTransactions.length?<Table headers={['Transaction','Insider','Title','Date','Filing','Shares','Price','Value','After','Code','Source']} rows={insiderTransactions.map(t=>[t.transaction_type??'—',t.insider_name??'—',t.insider_title??'—',t.transaction_date??'—',t.filing_date??'—',num(t.shares),money(t.price),money(t.value),num(t.shares_owned_after),t.transaction_code??'—',t.data_source??'—'])}/>:<Empty>No insider-transaction rows are stored for this stock.</Empty>}</Card>
  <Card id="sec-filings" eyebrow="SEC FILINGS" title="SEC Filing History">{secFilings.length?<Table headers={['Form','Filing Date','Period','Accepted','Primary Document','Description','Source']} rows={secFilings.map(f=>[f.form_type??'—',f.filing_date??'—',f.filing_period??'—',f.accepted_at??'—',f.primary_document??'—',f.filing_description??'—',f.filing_url?<a href={f.filing_url} target="_blank" rel="noreferrer">Open filing</a>:'—'])}/>:<Empty>No SEC filing rows are stored for this stock.</Empty>}</Card>
  <Card id="identifiers" eyebrow="IDENTIFIERS" title="Stock Identifiers"><Table headers={['Type','Value','Source','Verified']} rows={(identifiers??[]).map(x=>[x.identifier_type??'—',x.identifier_value??'—',x.source??'—',x.verified_at??'—'])}/></Card>
  <Card id="research-timeline" eyebrow="RESEARCH" title="Monthly & Quarterly Research">
   {monthlyResearch.length?monthlyResearch.map(r=><div className="research-entry" key={`m-${r.id}`}><h3>{renderValue(r.research_month)}</h3><p>Price {pct(r.price_change_percent)} · Revenue {pct(r.revenue_change_percent)} · EPS {pct(r.eps_change_percent)}</p><p>{r.ai_summary??r.fundamental_summary??r.technical_summary??'—'}</p></div>):null}
   {quarterlyResearch.length?quarterlyResearch.map(r=><div className="research-entry" key={`q-${r.id}`}><h3>{r.fiscal_period??renderValue(r.period_end)}</h3><p>{r.ai_summary??r.financial_summary??r.earnings_summary??'—'}</p><p>Guidance: {r.guidance_summary??'—'} · Risks: {r.risks_summary??'—'} · Catalysts: {r.catalysts_summary??'—'}</p></div>):!monthlyResearch.length&&<Empty>No monthly or quarterly research is stored.</Empty>}
  </Card>
  <Card id="data-quality" eyebrow="DATA QUALITY" title="Data Quality & Provenance">
   {quality?<Table headers={['Check Date','Identity','Market Data','Price History','Fundamentals','Technical','Earnings','Ownership','Filings','Overall','Missing','Stale','Validation Errors']} rows={[[quality.check_date,pct(quality.identity_score),pct(quality.market_data_score),pct(quality.price_history_score),pct(quality.fundamentals_score),pct(quality.technical_score),pct(quality.earnings_score),pct(quality.ownership_score),pct(quality.filings_score),pct(quality.overall_score),String(quality.missing_fields??'—'),String(quality.stale_fields??'—'),String(quality.validation_errors??'—')]]}/>:<Empty>No data-quality snapshot is stored for this stock.</Empty>}
   {provenance?.length?<><h3>Recent Provenance</h3><Table headers={['Retrieved','Entity','Field','Source','Verified','Source Time']} rows={provenance.map(p=>[p.retrieved_at??'—',p.entity_type??'—',p.data_field??'—',p.source_name??'—',p.is_verified?'Yes':'No',p.source_timestamp??'—'])}/></>:null}
  </Card>
 </div>
}
