import crypto from 'node:crypto';
const required=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY'];for(const n of required)if(!process.env[n])throw new Error(`${n} is not configured.`);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function db(table,{method='GET',params={},body,prefer='return=representation'}={}){const u=new URL(`${process.env.SUPABASE_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);for(let a=1;a<=4;a++){try{const r=await fetch(u,{method,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:prefer},body:body?JSON.stringify(body):undefined});const t=await r.text();if(r.ok)return t?JSON.parse(t):null;if(![408,429,500,502,503,504].includes(r.status)||a===4)throw new Error(`Supabase ${r.status}: ${t}`)}catch(e){if(a===4)throw e}await sleep(Math.min(1000*2**(a-1),8000))}}
async function ai(input){const key=process.env.OPENAI_API_KEY;if(!key)return null;const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4o-mini',temperature:.2,response_format:{type:'json_object'},messages:[{role:'system',content:'You are a financial research writer. Use ONLY the supplied verified structured data. Never invent prices, fundamentals, news, dates, earnings, targets, or facts. Write a balanced 500-700 word market analysis. Explain technicals, fundamentals, earnings/news context, quantitative prediction signals and risks. Predictions are estimates, not financial advice. Return JSON with title, summary, content.'},{role:'user',content:JSON.stringify(input)}]})});const t=await r.text();if(!r.ok)throw new Error(`OpenAI ${r.status}: ${t}`);return JSON.parse(JSON.parse(t).choices[0].message.content)}
if(!process.env.OPENAI_API_KEY){console.log(JSON.stringify({mode:'ai-article-generation',status:'skipped',reason:'OPENAI_API_KEY is not configured'}));process.exit(0)}
const limit=Number(process.env.ARTICLE_BATCH_SIZE||25);const stocks=await db('stocks',{params:{select:'id,symbol,company_name,sector,industry,description,market_cap',is_active:'eq.true',is_indexable:'eq.true',order:'market_cap.desc.nullslast',limit}});let generated=0,failed=0;
for(const s of stocks??[]){try{const [q,t,p,f,e,n,h]=await Promise.all([
 db('latest_quotes',{params:{select:'price,change_percent,volume,quote_timestamp',stock_id:`eq.${s.id}`,limit:1}}),db('technical_indicators',{params:{select:'*',stock_id:`eq.${s.id}`,timeframe:'eq.1d',limit:1}}),db('predictions',{params:{select:'horizon,predicted_price,predicted_change_percent,direction,confidence,feature_summary,prediction_time',stock_id:`eq.${s.id}`,order:'prediction_time.desc',limit:4}}),db('fundamentals',{params:{select:'*',stock_id:`eq.${s.id}`,order:'updated_at.desc',limit:1}}),db('earnings',{params:{select:'earnings_date,fiscal_period,eps_estimate,eps_actual,eps_surprise,revenue_estimate,revenue_actual,revenue_surprise',stock_id:`eq.${s.id}`,order:'earnings_date.desc',limit:4}}),db('news',{params:{select:'title,summary,source,published_at,sentiment,sentiment_score',stock_id:`eq.${s.id}`,order:'published_at.desc',limit:8}}),db('price_history',{params:{select:'timestamp,close',stock_id:`eq.${s.id}`,timeframe:'eq.1d',order:'timestamp.desc',limit:30}})]);
const data={stock:s,quote:q?.[0]??null,technical:t?.[0]??null,predictions:p??[],fundamentals:f?.[0]??null,earnings:e??[],news:n??[],recent_prices:(h??[]).reverse()};const article=await ai(data);if(!article?.content)continue;const hash=crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex');await db('ai_articles',{method:'DELETE',params:{stock_id:`eq.${s.id}`,article_type:'eq.market_analysis'},prefer:'return=minimal'});await db('ai_articles',{method:'POST',body:[{stock_id:s.id,article_type:'market_analysis',title:article.title,slug:`${s.symbol.toLowerCase()}-market-analysis`,content:article.content,summary:article.summary,model:process.env.OPENAI_MODEL||'gpt-4o-mini',source_data_hash:hash,generated_at:new Date().toISOString(),updated_at:new Date().toISOString(),is_published:true}],prefer:'return=minimal'});generated++}catch(e){failed++;console.error(`Article failed for ${s.symbol}:`,e.message)}}
console.log(JSON.stringify({mode:'ai-article-generation',requested:stocks?.length??0,generated,failed,model:process.env.OPENAI_MODEL||'gpt-4o-mini'},null,2));