import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { neon } from '@neondatabase/serverless';
const execFileAsync=promisify(execFile);
const sql=neon(process.env.NEON_DATABASE_URL);
const UA=process.env.SEC_USER_AGENT||'US Market AI research contact@example.com';
const MODE=process.env.SEC_MODE||'all';
const MAX=Number(process.env.SEC_MAX_STOCKS||0);
const TMP=fs.mkdtempSync(path.join(os.tmpdir(),'usmarketai-sec-'));
async function download(u,f){const r=await fetch(u,{headers:{'User-Agent':UA}});if(!r.ok)throw new Error('SEC '+r.status);await pipeline(Readable.fromWeb(r.body),fs.createWriteStream(f));}
async function unzip(f,d){await fs.promises.mkdir(d,{recursive:true});await execFileAsync('unzip',['-q','-o',f,'-d',d]);}
const cik=v=>String(v||'').replace(/\D/g,'').padStart(10,'0');
const date=v=>v?String(v).slice(0,10):null;
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const filingUrl=(c,a,d)=>'https://www.sec.gov/Archives/edgar/data/'+Number(c)+'/'+String(a).replace(/-/g,'')+'/'+(d||'');
async function universe(){const rows=await sql`SELECT id,symbol,cik FROM stocks WHERE is_active=true AND cik IS NOT NULL ORDER BY id`;return (MAX?rows.slice(0,MAX):rows).map(x=>({...x,cik:cik(x.cik)})).filter(x=>x.cik!=='0000000000');}
async function syncFilings(stocks){const z=path.join(TMP,'submissions.zip'),o=path.join(TMP,'submissions');console.log('SEC submissions bulk download');await download('https://www.sec.gov/Archives/edgar/daily-index/bulkdata/submissions.zip',z);await unzip(z,o);let count=0;for(const s of stocks){const f=path.join(o,'CIK'+s.cik+'.json');if(!fs.existsSync(f))continue;const j=JSON.parse(await fs.promises.readFile(f,'utf8')),r=j.filings&&j.filings.recent;if(!r)continue;for(let i=0;i<r.form.length;i++){const form=r.form[i],a=r.accessionNumber&&r.accessionNumber[i];if(!a||!/^(10-K|10-Q|8-K|20-F|40-F|6-K|DEF 14A|DEFA14A|DEF 14C|SC 13D|SC 13G|13F-HR|13F-HR\/A|3|4|5|144|S-1|S-3|S-4|424B|11-K)$/i.test(form))continue;const doc=r.primaryDocument&&r.primaryDocument[i]||null;await sql`INSERT INTO sec_filings(stock_id,cik,accession_number,form_type,filing_date,filing_period,accepted_at,primary_document,filing_url,filing_description,data_source,created_at) VALUES(${s.id},${s.cik},${a},${form},${date(r.filingDate&&r.filingDate[i])},${date(r.reportDate&&r.reportDate[i])},${r.accepted&&r.accepted[i]?new Date(r.accepted[i]):null},${doc},${filingUrl(s.cik,a,doc)},${r.primaryDocDescription&&r.primaryDocDescription[i]||null},'SEC_EDGAR_BULK',NOW()) ON CONFLICT(accession_number) DO UPDATE SET form_type=EXCLUDED.form_type,filing_date=EXCLUDED.filing_date,filing_period=EXCLUDED.filing_period,accepted_at=EXCLUDED.accepted_at,primary_document=EXCLUDED.primary_document,filing_url=EXCLUDED.filing_url,filing_description=EXCLUDED.filing_description`;count++;}}console.log('SEC filings upserted',count);}
function fact(f,names){for(const n of names){for(const t of ['us-gaap','ifrs-full']){const x=f&&f[t]&&f[t][n];if(x)return x}}return null}
function factRows(x){if(!x||!x.units)return[];const k=Object.keys(x.units)[0];return(x.units[k]||[]).filter(v=>/^(10-Q|10-K|20-F|40-F)$/.test(v.form));}
async function syncXbrl(stocks){const z=path.join(TMP,'companyfacts.zip'),o=path.join(TMP,'companyfacts');console.log('SEC companyfacts bulk download');await download('https://www.sec.gov/Archives/edgar/daily-index/xbrl/companyfacts.zip',z);await unzip(z,o);let earnings=0,divs=0;for(const s of stocks){const f=path.join(o,'CIK'+s.cik+'.json');if(!fs.existsSync(f))continue;const j=JSON.parse(await fs.promises.readFile(f,'utf8')),facts=j.facts||{};const eps=factRows(fact(facts,['EarningsPerShareDiluted','EarningsPerShareBasic'])),rev=factRows(fact(facts,['RevenueFromContractWithCustomerExcludingAssessedTax','Revenues'])),div=factRows(fact(facts,['PaymentsOfDividends','PaymentsOfDividendsCommonStock','CommonStockDividendsPerShareDeclared']));const periods=new Map();for(const x of [...eps,...rev]){const k=(x.fy||'')+'|'+(x.fp||'')+'|'+(x.end||'');if(!periods.has(k))periods.set(k,{end:x.end,filed:x.filed,fp:x.fp,eps:null,rev:null});}for(const x of eps){const k=(x.fy||'')+'|'+(x.fp||'')+'|'+(x.end||'');if(periods.has(k))periods.get(k).eps=num(x.val);}for(const x of rev){const k=(x.fy||'')+'|'+(x.fp||'')+'|'+(x.end||'');if(periods.has(k))periods.get(k).rev=num(x.val);}for(const p of periods.values()){if(p.eps==null&&p.rev==null)continue;await sql`INSERT INTO earnings(stock_id,earnings_date,fiscal_period,eps_actual,revenue_actual,data_source,created_at) VALUES(${s.id},${date(p.filed||p.end)},${p.fp||'reported'},${p.eps},${p.rev},'SEC_XBRL_BULK',NOW()) ON CONFLICT DO NOTHING`;earnings++;}for(const x of div){if(x.val==null||!x.end)continue;await sql`INSERT INTO dividends(stock_id,ex_date,declaration_date,amount,currency,data_source,created_at) VALUES(${s.id},NULL,${date(x.filed)},${num(x.val)},'USD','SEC_XBRL_BULK',NOW()) ON CONFLICT DO NOTHING`;divs++;} }console.log('Earnings rows',earnings,'dividend facts',divs);}
try{const stocks=await universe();console.log('SEC universe',stocks.length);if(MODE==='all'||MODE==='filings')await syncFilings(stocks);if(MODE==='all'||MODE==='xbrl')await syncXbrl(stocks);console.log('SEC bulk sync complete');}finally{process.exit(0);}