const required=['NEON_REST_URL','NEON_API_KEY'];
for(const n of required)if(!process.env[n])throw new Error(`${n} is not configured.`);
const SEC_USER_AGENT=process.env.SEC_USER_AGENT||'US Market AI research bot (GitHub: Mahi12091/us-market-ai)';
const SEC_BASE='https://data.sec.gov';const SEC_FILE_BASE='https://www.sec.gov';const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function sec(path){const u=new URL(path,SEC_BASE);for(let attempt=1;attempt<=5;attempt++){const r=await fetch(u,{headers:{'User-Agent':SEC_USER_AGENT,'Accept-Encoding':'gzip, deflate'}});const t=await r.text();if(r.ok)return t?JSON.parse(t):{};if(![408,429,500,502,503,504].includes(r.status)||attempt===5)throw new Error(`SEC ${r.status}: ${t.slice(0,500)}`);await sleep(r.status===429?3000:Math.min(1000*2**(attempt-1),10000));}}
async function secFile(path){const u=new URL(path,SEC_FILE_BASE);for(let attempt=1;attempt<=5;attempt++){const r=await fetch(u,{headers:{'User-Agent':SEC_USER_AGENT,'Accept-Encoding':'gzip, deflate'}});const t=await r.text();if(r.ok)return t?JSON.parse(t):{};if(![408,429,500,502,503,504].includes(r.status)||attempt===5)throw new Error(`SEC file ${r.status}: ${t.slice(0,500)}`);await sleep(r.status===429?3000:Math.min(1000*2**(attempt-1),10000));}}
async function db(table,{method='GET',params={},body,prefer='return=representation'}={}){const u=new URL(`${process.env.NEON_REST_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{method,headers:{apikey:process.env.NEON_API_KEY,Authorization:`Bearer ${process.env.NEON_API_KEY}`,'Content-Type':'application/json',Prefer:prefer},body:body?JSON.stringify(body):undefined});const t=await r.text();if(!r.ok)throw new Error(`Neon ${r.status}: ${t}`);return t?JSON.parse(t):null;}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}function latestFact(facts,tags,units=['USD','USD/shares','shares']){for(const tag of tags){const fact=facts?.facts?.['us-gaap']?.[tag]||facts?.facts?.dei?.[tag];if(!fact?.units)continue;for(const unit of units){const rows=fact.units[unit];if(!Array.isArray(rows))continue;const usable=rows.filter(x=>x?.val!=null&&x?.end&&(x.form==='10-K'||x.form==='10-Q'||x.form==='20-F'||x.form==='6-K'));usable.sort((a,b)=>String(b.end).localeCompare(String(a.end))||String(b.filed||'').localeCompare(String(a.filed||'')));if(usable[0])return usable[0];}}return null;}
function annualFacts(facts,tags,units=['USD','USD/shares']){for(const tag of tags){const fact=facts?.facts?.['us-gaap']?.[tag];if(!fact?.units)continue;for(const unit of units){const rows=(fact.units[unit]||[]).filter(x=>x?.val!=null&&x?.end&&x.form==='10-K'&&x.fp==='FY');if(rows.length)return rows.sort((a,b)=>String(b.end).localeCompare(String(a.end)));}}return [];}function valueAt(facts,tags){return num(latestFact(facts,tags)?.val)}function growth(current,previous){return current!=null&&previous!=null&&previous!==0?((current/previous)-1)*100:null;}
const stocks=await db('stocks',{params:{select:'id,symbol,market_cap,asset_type',is_active:'eq.true',limit:5000}});const quotes=await db('latest_quotes',{params:{select:'stock_id,price',limit:5000}});const priceById=new Map((quotes??[]).map(q=>[Number(q.stock_id),num(q.price)]));
function mapRowsToTickerMap(raw){if(Array.isArray(raw?.data)&&Array.isArray(raw?.fields)){const index=new Map(raw.fields.map((field,i)=>[String(field).toLowerCase(),i]));const tickerIndex=index.get('ticker'),cikIndex=index.get('cik');if(tickerIndex!=null&&cikIndex!=null)return new Map(raw.data.map(row=>[String(row?.[tickerIndex]??'').trim().toUpperCase(),String(row?.[cikIndex]??'').padStart(10,'0')]).filter(([ticker,cik])=>ticker&&cik!=='0000000000'));}if(Array.isArray(raw))return new Map(raw.map(x=>[String(x?.ticker||'').trim().toUpperCase(),String(x?.cik||x?.cik_str||'').padStart(10,'0')]).filter(([ticker,cik])=>ticker&&cik!=='0000000000'));return new Map(Object.values(raw||{}).map(x=>[String(x?.ticker||'').trim().toUpperCase(),String(x?.cik||x?.cik_str||'').padStart(10,'0')]).filter(([ticker,cik])=>ticker&&cik!=='0000000000'));}
async function loadTickerMap(){try{const raw=await secFile('/files/company_tickers_exchange.json');const map=mapRowsToTickerMap(raw);if(map.size<100)throw new Error(`unexpected mapping size ${map.size}`);return map;}catch(first){try{const raw=await secFile('/files/company_tickers.json');const map=mapRowsToTickerMap(raw);if(!map.size)throw new Error('empty ticker mapping');return map;}catch(second){throw new Error(`Unable to load SEC ticker/CIK mapping: ${first.message}; fallback: ${second.message}`);}}}
let tickerMap;try{tickerMap=await loadTickerMap();console.log(`Loaded ${tickerMap.size} SEC ticker/CIK associations.`);}catch(e){console.warn(`SEC ticker map unavailable: ${e.message}`);tickerMap=new Map();}
const rows=[],failures=[];const eligible=(stocks??[]).filter(s=>s.symbol&&String(s.asset_type||'stock')==='stock');let completed=0;
for(let offset=0;offset<eligible.length;offset+=5){const batch=eligible.slice(offset,offset+5);const results=await Promise.all(batch.map(async stock=>{const cik=tickerMap.get(String(stock.symbol).toUpperCase());if(!cik)return{stock,skip:'no-sec-cik'};try{const facts=await sec(`/api/xbrl/companyfacts/CIK${cik}.json`);const revenueFacts=annualFacts(facts,['RevenueFromContractWithCustomerExcludingAssessedTax','SalesRevenueNet','Revenues']);const epsFacts=annualFacts(facts,['EarningsPerShareDiluted','EarningsPerShareBasic'],['USD/shares']);const revenue=num(revenueFacts[0]?.val),previousRevenue=num(revenueFacts[1]?.val),eps=num(epsFacts[0]?.val),previousEps=num(epsFacts[1]?.val),net=valueAt(facts,['ProfitLoss','NetIncomeLoss','NetIncomeLossAvailableToCommonStockholdersBasic']),gross=valueAt(facts,['GrossProfit']),op=valueAt(facts,['OperatingIncomeLoss']),assets=valueAt(facts,['Assets']),equity=valueAt(facts,['StockholdersEquity','StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest']),debtCurrent=valueAt(facts,['LongTermDebtCurrent','ShortTermBorrowings']),debtNonCurrent=valueAt(facts,['LongTermDebtNoncurrent','LongTermDebt']),cfo=valueAt(facts,['NetCashProvidedByUsedInOperatingActivities']),capex=valueAt(facts,['PaymentsToAcquirePropertyPlantAndEquipment','PaymentsToAcquireProductiveAssets']),shares=valueAt(facts,['EntityCommonStockSharesOutstanding','CommonStockSharesOutstanding']),price=priceById.get(Number(stock.id)),marketCap=(price!=null&&shares!=null)?price*shares:num(stock.market_cap),debt=(debtCurrent||0)+(debtNonCurrent||0),fcf=cfo!=null&&capex!=null?cfo-Math.abs(capex):null,pe=price!=null&&eps!=null&&eps>0?price/eps:null,ps=marketCap!=null&&revenue!=null&&revenue>0?marketCap/revenue:null,pb=marketCap!=null&&equity!=null&&equity>0?marketCap/equity:null,de=equity!=null&&equity!==0?debt/equity:null,roe=net!=null&&equity!=null&&equity!==0?(net/equity)*100:null,roa=net!=null&&assets!=null&&assets!==0?(net/assets)*100:null,reportDate=revenueFacts[0]?.end||epsFacts[0]?.end||null;if(revenue==null&&net==null&&assets==null)return{stock,skip:'no-standardized-facts'};const fiscalPeriod=`annual-${revenueFacts[0]?.fy??epsFacts[0]?.fy??reportDate??'latest'}`;return{stock,row:{stock_id:Number(stock.id),fiscal_period:fiscalPeriod,market_cap:marketCap,enterprise_value:null,revenue,revenue_growth:growth(revenue,previousRevenue),gross_profit:gross,operating_income:op,net_income:net,eps,eps_growth:growth(eps,previousEps),pe_ratio:pe,forward_pe:null,peg_ratio:null,price_sales:ps,price_book:pb,debt_equity:de,roe,roa,free_cash_flow:fcf,dividend_yield:null,report_date:reportDate,data_source:'SEC EDGAR'}}catch(error){return{stock,error:error.message}}}));for(const result of results){completed++;if(result.row)rows.push(result.row);else failures.push({symbol:result.stock.symbol,reason:result.skip||result.error});}if(offset+5<eligible.length)await sleep(600)}
for(const row of rows)await db('fundamentals',{method:'POST',params:{on_conflict:'stock_id,fiscal_period'},prefer:'resolution=merge-duplicates,return=minimal',body:[row]});console.log(JSON.stringify({mode:'fundamentals-sync',stocks:stocks?.length??0,eligible:eligible.length,processed:completed,rows_written:rows.length,skipped_or_failed:failures.length,source:'SEC EDGAR',failures:failures.slice(0,20)},null,2));
