const required=['MASSIVE_API_KEY','SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY'];for(const n of required)if(!process.env[n])throw new Error(`${n} is not configured.`);
const api=process.env.MASSIVE_API_KEY;const base='https://api.massive.com';const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function massive(path){const u=new URL(path,base);u.searchParams.set('apiKey',api);for(let a=1;a<=4;a++){const r=await fetch(u);const t=await r.text();if(r.ok)return t?JSON.parse(t):{};if(![408,429,500,502,503,504].includes(r.status)||a===4)throw new Error(`Massive ${r.status}: ${t}`);await sleep(r.status===429?65000:Math.min(1000*2**(a-1),8000))}}
async function db(table,{method='GET',params={},body,prefer='return=representation'}={}){const u=new URL(`${process.env.SUPABASE_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{method,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:prefer},body:body?JSON.stringify(body):undefined});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t}`);return t?JSON.parse(t):null}
const stocks=await db('stocks',{params:{select:'id,symbol',is_active:'eq.true',limit:5000}});const ids=new Map((stocks??[]).map(s=>[s.symbol,Number(s.id)]));
const [ratios,income,cash,balance]=await Promise.all([
 massive('/stocks/financials/v1/ratios?limit=50000&sort=ticker.asc'),
 massive('/stocks/financials/v1/income-statements?limit=50000&sort=period_end.desc'),
 massive('/stocks/financials/v1/cash-flow-statements?limit=50000&sort=period_end.desc'),
 massive('/stocks/financials/v1/balance-sheets?limit=50000&sort=period_end.desc')
]);
const latest=(arr,key='period_end')=>{const m=new Map();for(const r of arr??[]){const t=r.tickers?.[0]??r.ticker;if(t&&!m.has(t))m.set(t,r)}return m};
const rm=new Map((ratios.results??[]).map(r=>[r.ticker,r]));const im=latest(income.results);const cm=latest(cash.results);const bm=latest(balance.results);const payload=[];
for(const [symbol,stockId] of ids){const r=rm.get(symbol),i=im.get(symbol),c=cm.get(symbol),b=bm.get(symbol);if(!r&&!i)continue;const revenue=Number(i?.revenue),net=Number(i?.net_income_loss_attributable_common_shareholders??i?.consolidated_net_income_loss),gross=Number(i?.gross_profit),op=Number(i?.operating_income),eps=Number(i?.diluted_earnings_per_share??i?.basic_earnings_per_share),fcf=Number(c?.free_cash_flow),pe=Number(r?.price_to_earnings),de=Number(r?.debt_to_equity),roe=Number(r?.return_on_equity),roa=Number(r?.return_on_assets);const period=i?.timeframe==='annual'?'annual':i?.period_end?`quarterly-${i.fiscal_year ?? ''}-${i.fiscal_quarter ?? ''}`:'ttm';payload.push({stock_id:stockId,fiscal_period:period,market_cap:r?.market_cap??null,enterprise_value:r?.enterprise_value??null,revenue:Number.isFinite(revenue)?revenue:null,revenue_growth:null,gross_profit:Number.isFinite(gross)?gross:null,operating_income:Number.isFinite(op)?op:null,net_income:Number.isFinite(net)?net:null,eps:Number.isFinite(eps)?eps:null,eps_growth:null,pe_ratio:Number.isFinite(pe)?pe:null,forward_pe:null,peg_ratio:null,price_sales:r?.price_to_sales??null,price_book:r?.price_to_book??null,debt_equity:Number.isFinite(de)?de:null,roe:Number.isFinite(roe)?roe:null,roa:Number.isFinite(roa)?roa:null,free_cash_flow:Number.isFinite(fcf)?fcf:null,dividend_yield:r?.dividend_yield??null,report_date:i?.period_end??r?.date??null,data_source:'Massive'});}
for(const row of payload){await db('fundamentals',{method:'POST',params:{on_conflict:'stock_id,fiscal_period'},prefer:'resolution=merge-duplicates,return=minimal',body:[row]})}
console.log(JSON.stringify({mode:'fundamentals-sync',stocks:ids.size,rows_written:payload.length,source:'Massive'},null,2));