-- Complete stock research data foundation
-- Adds statement-level metrics plus recurring AI research snapshots.

alter table public.fundamentals
  add column if not exists fiscal_year integer,
  add column if not exists period_type text,
  add column if not exists gross_margin numeric,
  add column if not exists operating_margin numeric,
  add column if not exists net_margin numeric,
  add column if not exists total_assets numeric,
  add column if not exists total_liabilities numeric,
  add column if not exists cash_and_equivalents numeric,
  add column if not exists total_debt numeric,
  add column if not exists shareholders_equity numeric,
  add column if not exists current_assets numeric,
  add column if not exists current_liabilities numeric,
  add column if not exists operating_cash_flow numeric,
  add column if not exists capital_expenditure numeric,
  add column if not exists fcf_margin numeric,
  add column if not exists shares_outstanding numeric,
  add column if not exists enterprise_value_to_revenue numeric,
  add column if not exists enterprise_value_to_ebitda numeric,
  add column if not exists earnings_yield numeric;

create table if not exists public.financial_statements (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  statement_type text not null check (statement_type in ('income_statement','balance_sheet','cash_flow')),
  period_type text not null check (period_type in ('quarterly','annual','ttm')),
  fiscal_period text not null,
  period_end date,
  revenue numeric,
  cost_of_revenue numeric,
  gross_profit numeric,
  operating_income numeric,
  pretax_income numeric,
  net_income numeric,
  eps_basic numeric,
  eps_diluted numeric,
  shares_basic numeric,
  shares_diluted numeric,
  cash_and_equivalents numeric,
  total_assets numeric,
  current_assets numeric,
  total_liabilities numeric,
  current_liabilities numeric,
  total_debt numeric,
  shareholders_equity numeric,
  operating_cash_flow numeric,
  capital_expenditure numeric,
  free_cash_flow numeric,
  data_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stock_id,statement_type,period_type,fiscal_period)
);

create table if not exists public.dividends (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  ex_date date,
  record_date date,
  payment_date date,
  declaration_date date,
  amount numeric,
  frequency text,
  currency text default 'USD',
  data_source text,
  created_at timestamptz not null default now(),
  unique(stock_id,ex_date,payment_date,amount)
);

create table if not exists public.ownership_snapshots (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  period_end date,
  shares_outstanding numeric,
  institutional_ownership_percent numeric,
  insider_ownership_percent numeric,
  float_shares numeric,
  data_source text,
  created_at timestamptz not null default now(),
  unique(stock_id,period_end)
);

create table if not exists public.monthly_stock_research (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  research_month date not null,
  price_change_percent numeric,
  revenue_change_percent numeric,
  eps_change_percent numeric,
  technical_summary text,
  fundamental_summary text,
  news_summary text,
  risk_summary text,
  catalyst_summary text,
  key_events jsonb,
  ai_summary text,
  model text,
  source_data_hash text,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stock_id,research_month)
);

create table if not exists public.quarterly_stock_research (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  fiscal_period text not null,
  period_end date,
  earnings_summary text,
  financial_summary text,
  guidance_summary text,
  management_commentary text,
  risks_summary text,
  catalysts_summary text,
  yoy_summary text,
  qoq_summary text,
  ai_summary text,
  model text,
  source_data_hash text,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stock_id,fiscal_period)
);

create index if not exists idx_financial_statements_stock_period on public.financial_statements(stock_id,period_end desc);
create index if not exists idx_dividends_stock_date on public.dividends(stock_id,ex_date desc);
create index if not exists idx_ownership_stock_date on public.ownership_snapshots(stock_id,period_end desc);
create index if not exists idx_monthly_research_stock_date on public.monthly_stock_research(stock_id,research_month desc);
create index if not exists idx_quarterly_research_stock_date on public.quarterly_stock_research(stock_id,period_end desc);

alter table public.financial_statements enable row level security;
alter table public.dividends enable row level security;
alter table public.ownership_snapshots enable row level security;
alter table public.monthly_stock_research enable row level security;
alter table public.quarterly_stock_research enable row level security;

create policy "public read financial statements" on public.financial_statements for select to anon, authenticated using (true);
create policy "public read dividends" on public.dividends for select to anon, authenticated using (true);
create policy "public read ownership snapshots" on public.ownership_snapshots for select to anon, authenticated using (true);
create policy "public read monthly stock research" on public.monthly_stock_research for select to anon, authenticated using (true);
create policy "public read quarterly stock research" on public.quarterly_stock_research for select to anon, authenticated using (true);
