-- 3spread raw traceability tables
-- These tables preserve the provider response used to build normalized research data.

create table if not exists public.threespread_financial_statements (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  ticker text not null,
  block_id text not null,
  filing_id text,
  cik text,
  form_type text,
  accession_num text,
  source_url text,
  accepted_time text,
  statement_type text,
  spine text,
  spine_confidence numeric,
  spine_low_conf numeric,
  period_of_report text,
  period_end text,
  period_length numeric,
  period_type text,
  fiscal_year integer,
  fiscal_quarter integer,
  filing_fiscal_year integer,
  is_comparative boolean,
  derived boolean,
  is_valid boolean,
  score_composite numeric,
  scores jsonb,
  currency text,
  statement_json jsonb,
  raw_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stock_id, block_id)
);

create table if not exists public.threespread_statement_line_items (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  ticker text not null,
  block_id text not null,
  filing_id text,
  statement_type text,
  section text,
  item_key text not null,
  label text,
  value numeric,
  source text,
  members jsonb,
  currency text,
  period_end text,
  period_type text,
  fiscal_year integer,
  fiscal_quarter integer,
  raw_item jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stock_id, block_id, item_key)
);

create table if not exists public.threespread_metrics (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  ticker text not null,
  period_end text not null,
  period_of_report text,
  period_length numeric,
  period_type text,
  fiscal_year integer,
  fiscal_quarter integer,
  category text not null,
  value numeric,
  currency text,
  unit text,
  spine text,
  derived boolean,
  is_valid boolean,
  raw_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stock_id, category, period_end, period_type)
);

create table if not exists public.threespread_ratios (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  ticker text not null,
  ratio_category text,
  ratio_name text not null,
  value numeric,
  value_pctile numeric,
  missing_inputs jsonb,
  period_end text not null,
  period_of_report text,
  period_length numeric,
  period_type text,
  fiscal_year integer,
  fiscal_quarter integer,
  spine text,
  derived boolean,
  is_valid boolean,
  raw_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stock_id, ratio_name, period_end, period_type)
);

create index if not exists idx_3s_fs_stock_period
  on public.threespread_financial_statements(stock_id, period_end);
create index if not exists idx_3s_line_items_stock_period
  on public.threespread_statement_line_items(stock_id, period_end);
create index if not exists idx_3s_metrics_stock_period
  on public.threespread_metrics(stock_id, period_end);
create index if not exists idx_3s_ratios_stock_period
  on public.threespread_ratios(stock_id, period_end);
